package util;

import model.TileType;

public final class Constant {
    public static final String MULTICAST_GROUP = "224.0.0.1";
    public static final int MULTICAST_PORT = 4446;
    public static final int SERVER_PORT = 4445;
    public static final int SCREEN_WIDTH = 1440;
    public static final int SCREEN_HEIGHT = 810;
    public static final float PLAYER_SPEED = 100f;
    public static final TileType[][] MAP = {
            {TileType.WALL, TileType.WALL, TileType.WALL, TileType.WALL, TileType.WALL, TileType.WALL, TileType.WALL, TileType.WALL, TileType.WALL, TileType.WALL, TileType.WALL, TileType.WALL, TileType.WALL, TileType.WALL, TileType.WALL, TileType.WALL, TileType.WALL, TileType.WALL, TileType.WALL, TileType.WALL, TileType.WALL, TileType.WALL, TileType.WALL, TileType.WALL, TileType.WALL, TileType.WALL, TileType.WALL, TileType.WALL, TileType.WALL, TileType.WALL, TileType.WALL, TileType.WALL},
            {TileType.WALL, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.WALL},
            {TileType.WALL, TileType.NONE, TileType.WALL, TileType.NONE, TileType.WALL, TileType.WALL, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.WALL, TileType.NONE, TileType.WALL, TileType.NONE, TileType.NONE, TileType.WALL, TileType.NONE, TileType.NONE, TileType.WALL, TileType.NONE, TileType.NONE, TileType.NONE, TileType.WALL, TileType.NONE, TileType.WALL, TileType.NONE, TileType.NONE, TileType.WALL, TileType.NONE, TileType.NONE, TileType.WALL, TileType.WALL},
            {TileType.WALL, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.WALL},
            {TileType.WALL, TileType.NONE, TileType.WALL, TileType.NONE, TileType.NONE, TileType.NONE, TileType.WALL, TileType.WALL, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.WALL, TileType.NONE, TileType.NONE, TileType.WALL, TileType.WALL, TileType.NONE, TileType.NONE, TileType.NONE, TileType.WALL, TileType.NONE, TileType.NONE, TileType.WALL, TileType.NONE, TileType.NONE, TileType.NONE, TileType.WALL, TileType.NONE, TileType.NONE, TileType.WALL},
            {TileType.WALL, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.WALL},
            {TileType.WALL, TileType.NONE, TileType.NONE, TileType.WALL, TileType.NONE, TileType.WALL, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.WALL, TileType.NONE, TileType.NONE, TileType.NONE, TileType.WALL, TileType.WALL, TileType.NONE, TileType.NONE, TileType.NONE, TileType.WALL, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.WALL, TileType.WALL, TileType.NONE, TileType.NONE, TileType.WALL},
            {TileType.WALL, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.WALL},
            {TileType.WALL, TileType.WALL, TileType.WALL, TileType.NONE, TileType.WALL, TileType.NONE, TileType.WALL, TileType.NONE, TileType.NONE, TileType.NONE, TileType.WALL, TileType.WALL, TileType.NONE, TileType.NONE, TileType.WALL, TileType.NONE, TileType.NONE, TileType.WALL, TileType.WALL, TileType.NONE, TileType.NONE, TileType.WALL, TileType.WALL, TileType.NONE, TileType.WALL, TileType.WALL, TileType.NONE, TileType.NONE, TileType.WALL, TileType.WALL, TileType.NONE, TileType.WALL},
            {TileType.WALL, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.WALL},
            {TileType.WALL, TileType.NONE, TileType.WALL, TileType.WALL, TileType.NONE, TileType.NONE, TileType.WALL, TileType.NONE, TileType.NONE, TileType.WALL, TileType.NONE, TileType.NONE, TileType.WALL, TileType.NONE, TileType.WALL, TileType.NONE, TileType.WALL, TileType.NONE, TileType.WALL, TileType.WALL, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.WALL, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.WALL, TileType.WALL, TileType.WALL},
            {TileType.WALL, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.WALL},
            {TileType.WALL, TileType.WALL, TileType.NONE, TileType.NONE, TileType.WALL, TileType.NONE, TileType.WALL, TileType.NONE, TileType.WALL, TileType.NONE, TileType.NONE, TileType.NONE, TileType.WALL, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.WALL, TileType.NONE, TileType.NONE, TileType.NONE, TileType.WALL, TileType.NONE, TileType.WALL, TileType.NONE, TileType.WALL, TileType.WALL, TileType.NONE, TileType.NONE, TileType.WALL, TileType.NONE, TileType.WALL},
            {TileType.WALL, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.WALL},
            {TileType.WALL, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.WALL},
            {TileType.WALL, TileType.NONE, TileType.WALL, TileType.NONE, TileType.NONE, TileType.NONE, TileType.WALL, TileType.NONE, TileType.WALL, TileType.WALL, TileType.NONE, TileType.WALL, TileType.WALL, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.WALL, TileType.NONE, TileType.NONE, TileType.WALL, TileType.NONE, TileType.NONE, TileType.NONE, TileType.WALL, TileType.WALL, TileType.WALL, TileType.NONE, TileType.WALL, TileType.NONE, TileType.NONE, TileType.WALL},
            {TileType.WALL, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.NONE, TileType.WALL},
            {TileType.WALL, TileType.WALL, TileType.WALL, TileType.WALL, TileType.WALL, TileType.WALL, TileType.WALL, TileType.WALL, TileType.WALL, TileType.WALL, TileType.WALL, TileType.WALL, TileType.WALL, TileType.WALL, TileType.WALL, TileType.WALL, TileType.WALL, TileType.WALL, TileType.WALL, TileType.WALL, TileType.WALL, TileType.WALL, TileType.WALL, TileType.WALL, TileType.WALL, TileType.WALL, TileType.WALL, TileType.WALL, TileType.WALL, TileType.WALL, TileType.WALL, TileType.WALL}
    };
    public static final int NUM_OF_TILES_IN_WIDTH = MAP[0].length;
    public static final int NUM_OF_TILES_IN_HEIGHT = MAP.length;
}
